import { CategoryInfo, HotelProfileConfig, MenuItem, NotificationItem, Order, TableQR, ThemeConfig, UserProfile } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Chef Marco',
    role: 'Kitchen',
    department: 'Kitchen',
    email: 'chef.marco@hoteladmin.com',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastLogin: 'Active now',
  },
  {
    id: 'user-2',
    name: 'Elena Rodriguez',
    role: 'Manager',
    department: 'Front of House',
    email: 'elena.r@hoteladmin.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastLogin: 'Today, 08:30 AM',
  },
  {
    id: 'user-3',
    name: 'David Lee',
    role: 'Kitchen',
    department: 'Grill Station',
    email: 'david.l@hoteladmin.com',
    avatar: '',
    initials: 'DL',
    status: 'Active',
    lastLogin: 'Yesterday, 14:15 PM',
  },
  {
    id: 'user-4',
    name: 'Michael Chen',
    role: 'Waiter',
    department: 'Main Dining',
    email: 'm.chen@hoteladmin.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Inactive',
    lastLogin: 'Oct 24, 2023',
  },
  {
    id: 'user-5',
    name: 'Sophia Laurent',
    role: 'Sommelier',
    department: 'Beverage & Cellar',
    email: 'sophia.l@hoteladmin.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastLogin: 'Today, 11:20 AM',
  },
  {
    id: 'user-6',
    name: 'Lucas Vance',
    role: 'Waiter',
    department: 'Terrace & Lounge',
    email: 'lucas.v@hoteladmin.com',
    avatar: '',
    initials: 'LV',
    status: 'Active',
    lastLogin: 'Today, 12:45 PM',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-4092',
    orderNumber: '4092',
    tableNumber: '12',
    isVip: true,
    timeAgo: '2m ago',
    timestamp: Date.now() - 2 * 60 * 1000,
    status: 'new',
    totalRevenue: 185.00,
    items: [
      { id: 'i1', name: 'Wagyu Burger', qty: 2, specialAlert: 'Med Rare, No Onions', price: 48 },
      { id: 'i2', name: 'Truffle Fries', qty: 1, price: 16 },
    ],
  },
  {
    id: 'ord-4091',
    orderNumber: '4091',
    tableNumber: '04',
    timeAgo: '7m ago',
    timestamp: Date.now() - 7 * 60 * 1000,
    status: 'new',
    totalRevenue: 210.50,
    items: [
      { id: 'i3', name: 'Grilled Salmon', qty: 1, price: 42 },
      { id: 'i4', name: 'Caesar Salad', qty: 1, specialAlert: 'Dressing on side', price: 22 },
    ],
  },
  {
    id: 'ord-4089',
    orderNumber: '4089',
    tableNumber: 'Bar',
    timeAgo: '12m ago',
    isAlert: true,
    timestamp: Date.now() - 12 * 60 * 1000,
    status: 'new',
    totalRevenue: 54.00,
    items: [
      { id: 'i5', name: 'Oysters (Half Dozen)', qty: 3, price: 36 },
      { id: 'i6', name: 'Signature Martini', qty: 2, price: 18 },
    ],
  },
  {
    id: 'ord-4088',
    orderNumber: '4088',
    tableNumber: '08',
    timeAgo: '18m ago',
    startedTimeAgo: 'Started 8m ago',
    timestamp: Date.now() - 18 * 60 * 1000,
    status: 'preparing',
    totalRevenue: 145.00,
    items: [
      { id: 'i7', name: 'Ribeye Steak', qty: 1, prepChecked: true, price: 65 },
      { id: 'i8', name: 'Lobster Tail', qty: 1, prepChecked: false, price: 55 },
    ],
  },
  {
    id: 'ord-4086',
    orderNumber: '4086',
    tableNumber: '15',
    timeAgo: '30m ago',
    startedTimeAgo: 'Started 22m ago',
    isAlert: true,
    timestamp: Date.now() - 30 * 60 * 1000,
    status: 'preparing',
    totalRevenue: 380.00,
    items: [
      { id: 'i9', name: 'Tasting Menu (Set A)', qty: 4, specialAlert: '1x Gluten Free', prepChecked: false, price: 95 },
    ],
  },
  {
    id: 'ord-4085',
    orderNumber: '4085',
    tableNumber: '02',
    timeAgo: '25m ago',
    startedTimeAgo: 'Started 18m ago',
    runnerWaiting: true,
    timestamp: Date.now() - 25 * 60 * 1000,
    status: 'ready',
    totalRevenue: 98.00,
    items: [
      { id: 'i10', name: 'Truffle Pappardelle', qty: 2, prepChecked: true, price: 38 },
      { id: 'i11', name: 'Tiramisu Classico', qty: 1, prepChecked: true, price: 22 },
    ],
  },
  {
    id: 'ord-4084',
    orderNumber: '4084',
    tableNumber: '09',
    timeAgo: '35m ago',
    startedTimeAgo: 'Started 24m ago',
    runnerWaiting: true,
    timestamp: Date.now() - 35 * 60 * 1000,
    status: 'ready',
    totalRevenue: 165.00,
    items: [
      { id: 'i12', name: 'Seared Hokkaido Scallops', qty: 2, prepChecked: true, price: 32 },
      { id: 'i13', name: 'Chablis Premier Cru', qty: 1, prepChecked: true, price: 101 },
    ],
  },
  // Completed history items
  {
    id: 'ord-4083',
    orderNumber: '4083',
    tableNumber: 'Table 12 (VIP)',
    timeAgo: '1h ago',
    timeCompleted: '19:42 PM',
    timestamp: Date.now() - 60 * 60 * 1000,
    status: 'completed',
    totalRevenue: 185.00,
    items: [
      { id: 'c1', name: 'Truffle Pappardelle', qty: 2 },
      { id: 'c2', name: 'Wagyu Carpaccio', qty: 1 },
    ],
  },
  {
    id: 'ord-4082',
    orderNumber: '4082',
    tableNumber: 'Table 04',
    timeAgo: '1h 10m ago',
    timeCompleted: '19:38 PM',
    timestamp: Date.now() - 70 * 60 * 1000,
    status: 'completed',
    totalRevenue: 210.50,
    items: [
      { id: 'c3', name: 'Wagyu Prime Rib', qty: 2 },
      { id: 'c4', name: 'Cabernet Sauvignon', qty: 1 },
    ],
  },
  {
    id: 'ord-4081',
    orderNumber: '4081',
    tableNumber: 'Bar 02',
    timeAgo: '1h 25m ago',
    timeCompleted: '19:25 PM',
    timestamp: Date.now() - 85 * 60 * 1000,
    status: 'completed',
    totalRevenue: 54.00,
    items: [
      { id: 'c5', name: 'Signature Cocktails', qty: 2 },
      { id: 'c6', name: 'Truffle Nuts', qty: 1 },
    ],
  },
  {
    id: 'ord-4080',
    orderNumber: '4080',
    tableNumber: 'Table 08',
    timeAgo: '1h 40m ago',
    timeCompleted: '19:15 PM',
    timestamp: Date.now() - 100 * 60 * 1000,
    status: 'completed',
    totalRevenue: 42.00,
    items: [
      { id: 'c7', name: 'Gold Leaf Dome', qty: 1 },
      { id: 'c8', name: 'Espresso Romano', qty: 2 },
    ],
  },
];

export const INITIAL_CATEGORIES: CategoryInfo[] = [
  { id: 'cat-1', name: 'Appetizers', count: 12 },
  { id: 'cat-2', name: 'Mains', count: 24 },
  { id: 'cat-3', name: 'Sides', count: 8 },
  { id: 'cat-4', name: 'Desserts', count: 10 },
  { id: 'cat-5', name: 'Drinks', count: 35 },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'Wagyu Beef Tartare',
    category: 'Appetizers',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Garde Manger',
    description: 'Hand-cut A5 Miyazaki wagyu, cured quail egg yolk, smoked bone marrow emulsion, toasted brioche.',
    allergens: ['Egg', 'Gluten'],
    tags: ['Chef Signature', 'Raw Bar'],
    ordersCount: 38,
  },
  {
    id: 'm2',
    name: 'Seared Hokkaido Scallops',
    category: 'Appetizers',
    price: 32.00,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80',
    isAvailable: false,
    isSoldOut: true,
    station: 'Fish Station',
    description: 'Pan-seared jumbo scallops, cauliflower velouté, black truffle pearls, micro sea fennel.',
    allergens: ['Shellfish', 'Dairy'],
    tags: ['Sold Out', 'Seasonal'],
    ordersCount: 22,
  },
  {
    id: 'm3',
    name: 'Truffle Burrata',
    category: 'Appetizers',
    price: 28.00,
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Garde Manger',
    description: 'Artisanal Pugliese burrata, heirloom tomatoes, fresh black summer truffle, 25-year aged balsamic.',
    allergens: ['Dairy'],
    tags: ['Vegetarian', 'Popular'],
    ordersCount: 45,
  },
  {
    id: 'm4',
    name: 'Truffle Arancini',
    category: 'Appetizers',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Fry Station',
    description: 'Wild mushroom risotto, mozzarella core, black truffle aioli, shaved parmigiano reggiano.',
    allergens: ['Dairy', 'Gluten'],
    tags: ['Best Seller'],
    ordersCount: 51,
  },
  {
    id: 'm5',
    name: 'Wagyu Beef Carpaccio',
    category: 'Appetizers',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Garde Manger',
    description: 'Thinly sliced premium wagyu, shaved parmesan, capers, baby arugula, extra virgin olive oil.',
    allergens: ['Dairy'],
    tags: ['Gluten Free'],
    ordersCount: 31,
  },
  {
    id: 'm6',
    name: 'Truffle Pappardelle',
    category: 'Mains',
    price: 38.00,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281560?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Pasta Station',
    description: 'Handcrafted ribbon pasta, Norcia black truffles, cultured butter sauce, 36-month parmigiano.',
    allergens: ['Dairy', 'Gluten', 'Egg'],
    tags: ['Top Selling', 'Signature'],
    ordersCount: 42,
  },
  {
    id: 'm7',
    name: 'Wagyu Prime Rib',
    category: 'Mains',
    price: 68.00,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Grill Station',
    description: 'Dry-aged 45 days, rosemary garlic butter crust, bone marrow jus, roasted shallots.',
    allergens: ['Dairy'],
    tags: ['Grill Special'],
    ordersCount: 28,
  },
  {
    id: 'm8',
    name: 'Gold Leaf Dome',
    category: 'Desserts',
    price: 26.00,
    image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Pastry',
    description: 'Valrhona 70% dark chocolate mousse, hazelnut praline crunch, 24k edible gold leaf, raspberry coulis.',
    allergens: ['Dairy', 'Nuts', 'Egg'],
    tags: ['Luxury Dessert'],
    ordersCount: 19,
  },
  {
    id: 'm9',
    name: 'Lobster Tail Thermidor',
    category: 'Mains',
    price: 56.00,
    image: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Fish Station',
    description: 'Maine lobster tail, cognac mustard cream sauce, gruyere gratin, fine herbs.',
    allergens: ['Shellfish', 'Dairy', 'Alcohol'],
    tags: ['Classic'],
    ordersCount: 25,
  },
  {
    id: 'm10',
    name: 'Truffle Fries',
    category: 'Sides',
    price: 16.00,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Fry Station',
    description: 'Hand-cut Idaho potatoes, black truffle oil, parmigiano reggiano, fresh chives.',
    allergens: ['Dairy'],
    tags: ['Side'],
    ordersCount: 60,
  },
  {
    id: 'm11',
    name: 'Signature Martini',
    category: 'Drinks',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isSoldOut: false,
    station: 'Bar',
    description: 'Botanist Gin or Grey Goose, vermouth rinse, hand-stuffed blue cheese Sicilian olives.',
    allergens: ['Alcohol', 'Dairy'],
    tags: ['Bar Special'],
    ordersCount: 34,
  },
];

export const INITIAL_TABLES: TableQR[] = [
  {
    id: 'tbl-1',
    tableNumber: 'Table 01',
    zone: 'TERRACE',
    status: 'Active',
    previewType: 'table',
    codeGenerated: true,
    scansToday: 24,
  },
  {
    id: 'tbl-2',
    tableNumber: 'Table 02',
    zone: 'MAIN DINING',
    status: 'Active',
    previewType: 'table',
    codeGenerated: true,
    scansToday: 38,
  },
  {
    id: 'tbl-3',
    tableNumber: 'Table 03',
    zone: 'MAIN DINING',
    status: 'Active',
    previewType: 'tablet',
    codeGenerated: true,
    scansToday: 19,
  },
  {
    id: 'tbl-4',
    tableNumber: 'Table 04',
    zone: 'BAR AREA',
    status: 'Inactive',
    previewType: 'minimal',
    codeGenerated: false,
    scansToday: 0,
  },
  {
    id: 'tbl-5',
    tableNumber: 'Table 05 (VIP)',
    zone: 'VIP LOUNGE',
    status: 'Active',
    previewType: 'table',
    codeGenerated: true,
    scansToday: 12,
  },
  {
    id: 'tbl-6',
    tableNumber: 'Table 06',
    zone: 'TERRACE',
    status: 'Active',
    previewType: 'tablet',
    codeGenerated: true,
    scansToday: 15,
  },
];

export const INITIAL_THEME: ThemeConfig = {
  primaryColor: '#D4AF37',
  backgroundColor: '#F8FAFC',
  primaryFont: 'Inter (Default)',
  guestMenuLogo: 'Adama Hotel Dining',
  layoutTemplate: 'luxury-cards',
  restaurantName: 'Adama Hotel Dining',
  tagline: 'Table 12 • Dinner Menu',
};

export const INITIAL_HOTEL_PROFILE: HotelProfileConfig = {
  hotelName: 'Adama Hotel',
  slogan: 'Culinary Excellence, Redefined.',
  primaryAddress: '1200 Luxury Avenue\nMetropolis City, NY 10001',
  officialWebsite: 'https://www.adama.com',
  operatingHours: [
    { day: 'Monday', openTime: '07:00 AM', closeTime: '11:00 PM', kitchenCutoff: '10:15 PM', isOpen: true },
    { day: 'Tuesday', openTime: '07:00 AM', closeTime: '11:00 PM', kitchenCutoff: '10:15 PM', isOpen: true },
    { day: 'Wednesday', openTime: '07:00 AM', closeTime: '11:00 PM', kitchenCutoff: '10:15 PM', isOpen: true },
    { day: 'Thursday', openTime: '07:00 AM', closeTime: '11:30 PM', kitchenCutoff: '10:45 PM', isOpen: true },
    { day: 'Friday', openTime: '07:00 AM', closeTime: '01:00 AM', kitchenCutoff: '11:30 PM', isOpen: true },
    { day: 'Saturday', openTime: '08:00 AM', closeTime: '01:00 AM', kitchenCutoff: '11:30 PM', isOpen: true },
    { day: 'Sunday', openTime: '08:00 AM', closeTime: '10:30 PM', kitchenCutoff: '09:45 PM', isOpen: true },
  ],
  contactInfo: {
    reservationsPhone: '+1 (212) 555-0198',
    conciergeEmail: 'reservations@adama.com',
    emergencyManager: '+1 (212) 555-0199',
    socialHandle: '@adamaofficial',
  },
  languages: [
    { code: 'en', name: 'English (US)', flag: '🇺🇸', isEnabled: true, isDefault: true },
    { code: 'fr', name: 'Français', flag: '🇫🇷', isEnabled: true },
    { code: 'es', name: 'Español', flag: '🇪🇸', isEnabled: true },
    { code: 'ja', name: '日本語', flag: '🇯🇵', isEnabled: true },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪', isEnabled: false },
    { code: 'ar', name: 'العربية', flag: '🇦🇪', isEnabled: false },
  ],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    title: 'New High Priority Order #4089',
    description: 'Bar area requested urgent rush on Signature Martini & Oysters.',
    time: '2m ago',
    type: 'order',
    isRead: false,
    orderId: 'ord-4089',
  },
  {
    id: 'n2',
    title: 'Order #4085 Ready for Pickup',
    description: 'Table 02 waiting on runner for Truffle Pappardelle.',
    time: '6m ago',
    type: 'kitchen',
    isRead: false,
    orderId: 'ord-4085',
  },
  {
    id: 'n3',
    title: 'Item Stock Update',
    description: 'Seared Hokkaido Scallops marked as SOLD OUT by Garde Manger.',
    time: '18m ago',
    type: 'system',
    isRead: true,
  },
  {
    id: 'n4',
    title: 'Elena Rodriguez Logged In',
    description: 'Manager session opened on Main Terminal #1.',
    time: '45m ago',
    type: 'staff',
    isRead: true,
  },
];
